[package]
name = "mrc-workout-creator"
version = "0.3.0"
edition = "2021"
authors = ["Tim Toebrock"]
license = "MIT"
description = """
Create workouts in the MRC format.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.9.0", features = ["async-std", "debug", "canvas"] }
rfd = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-std = "1.0"
directories-next = "2.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["Window", "Storage"] }
wasm-timer = "0.2"
